apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gjnj7ne62-nodejs
  janus-idp.io/tekton: gjnj7ne62-nodejs
  backstage.io/kubernetes-id: gjnj7ne62-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gjnj7ne62-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
