apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gjnj7ne62-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gjnj7ne62-nodejs 
  name: gjnj7ne62-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gjnj7ne62-nodejs 
